sudo: false
language: python
python:
  - "2.7"

cache: pip
 

addons:
  apt:
    packages:
    - build-essential
    - curl
    - ncbi-blast+
    - muscle

before_install:
  - git clone https://github.com/Linuxbrew/brew.git ~/.linuxbrew
  - export PATH="$HOME/.linuxbrew/bin:$PATH"
  - export MANPATH="$HOME/.linuxbrew/share/man:$MANPATH"
  - export INFOPATH="$HOME/.linuxbrew/share/info:$INFOPATH"
  - brew tap homebrew/science
  - brew install bwa samtools

install: 
  - pip install Cython
  - pip install coveralls
  - pip install -r requirements.txt
  - python setup.py install


script: 
  - coverage run --source=vcf-kit py.test


after_success:
  - coveralls
