language: python
python:
  - "2.7"

install: 
  - pip install Cython
  - pip install -r requirements.txt
  - python setup.py install
addons:
  apt:
    packages:
    - bwa
    - samtools

script: 
  - py.test 