language: python
python:
  - "2.7"
cache:
  - pip
  

install: 
  - pip install Cython
  - pip install -r requirements.txt
  - python setup.py install
addons:
  apt:
    packages:
    - bwa
    - samtools
    - tabix
    - ncbi-blast+
    - muscle

script: 
  - py.test 