language: python
python:
  - "2.7"

install: 
  - pip install -r requirements.txt
  - pip install https://github.com/brentp/cyvcf2/archive/v0.1.9.tar.gz
addons:
  apt:
    packages:
    - bwa
    - samtools

script: 
  - py.test test.py

sudo: false