language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt"
addons:
  apt:
    packages:
    - bwa
    - samtools
# command to run tests
script: 
  - py.test test.py
sudo: false