site_name: vcf-kit
theme: readthedocs
pages:
  - Home: index.md
  - about: about.md
  - genome: 'genome.md'
  - phylo: 'phylo.md'
  - hmm: hmm.md
  - tajima: tajima.md
repo_url: https://github.com/Andersenlab/vcf-kit
site_favicon: favicon.png
markdown_extensions:
    - codehilite
    - toc:
        permalink: True
    - fenced_code
    - sane_lists


markdown_extensions:
    - admonition: