site_name: VCF-kit
theme: readthedocs
pages:
  - Home: index.md
  - calc: 'calc.md'
  - call: 'call.md'
  - filter: 'filter.md'
  - geno: 'geno.md'
  - genome: 'genome.md'
  - hmm: hmm.md
  - phylo: 'phylo.md'
  - primer: 'primer.md'
  - rename: rename.md
  - tajima: tajima.md
  - vcf2sql: vcf2sql.md
  - vcf2tsv: vcf2tsv.md
repo_url: https://github.com/Andersenlab/vcf-kit
site_favicon: favicon.png
markdown_extensions:
    - codehilite
    - toc:
        permalink: True
    - fenced_code
    - sane_lists

markdown_extensions:
    - admonition: