{% set name = "vcf-kit" %}
{% set version = "0.1.7" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: e44319bc057ff4f90cc3a777bb6b1794e5dc3dcf56fe2753fee199f782fed6b6

build:
  number: 0
  entry_points:
    - vk=vcfkit.vk:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - pytest
    - pytest-cov
  host:
    - awesome-slugify
    - biopython
    - clint
    - cython >=0.24.1
    - cyvcf2 >=0.6.5
    - docopt
    - intervaltree ==2.1.0
    - jinja2
    - matplotlib
    - networkx ==1.11
    - numpy
    - pip
    - python
    - requests
    - scipy
    - setuptools
    - tabulate
  run:
    - awesome-slugify
    - biopython
    - clint
    - cython >=0.24.1
    - cyvcf2 >=0.6.5
    - docopt
    - intervaltree ==2.1.0
    - jinja2
    - matplotlib
    - networkx ==1.11
    - numpy
    - python
    - requests
    - scipy
    - setuptools
    - tabulate
    - numpy
    - biopython
    - bwa
    - samtools
    - bcftools
    - vcftools
    - blast
    - primer3=2.5.0

test:
  imports:
    - vcfkit
    - vcfkit.utils
  commands:
    - vk --help
  requires:
    - coveralls
    - pytest

about:
  home: "https://github.com/AndersenLab/VCF-kit"
  license: MIT
  license_family: MIT
  summary: "Assorted utilities for the variant call format"
  doc_url: https://vcf-kit.readthedocs.io/en/latest

extra:
  recipe-maintainers:
    - danielecook
