{% set name = "vcf-kit" %}
{% set version = "0.2.91" %}
package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/VCF-kit-0.2.7.tar.gz"
  sha256: fea49139e780b5e04f5dcdc02af630dcdfeb624706b0c8af01ba33616a159ae1

build:
  number: 0
  entry_points:
    - vk=vcfkit.vk:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python==3.6
    - pip
    - awesome-slugify
    - biopython
    - clint
    - cython
    - cyvcf2
    - docopt
    - intervaltree
    - jinja2
    - matplotlib
    - networkx
    - numpy
    - pomegranate
    - python
    - requests
    - scipy
    - setuptools
    - tabulate
    - pytest
    - pytest-runner
  run:
    - python>=3.6
    - pip
    - awesome-slugify
    - biopython
    - clint
    - cython
    - cyvcf2
    - docopt
    - intervaltree
    - jinja2
    - matplotlib
    - networkx
    - numpy
    - pomegranate
    - python
    - requests
    - scipy
    - setuptools
    - tabulate
    - pytest
    - pytest-runner

test:
  imports:
    - vcfkit
    - vcfkit.utils
  commands:
    - vk --help
  requires:
    - coveralls
    - pytest
    - pytest-runner

about:
  home: The package home page
  license: MIT
  license_family: MIT
  license_file: 
  summary: "Assorted utilities for the variant call format"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - danielecook
