# Build dockerfile on change
name: Build and Test

on:
  - push

jobs:
  test_and_publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install curl headers
      run: |
        sudo apt-get install libcurl4-openssl-dev
    
    - uses: goanpeca/setup-miniconda@v1
      with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
  
    - name: Install dependencies
      run: | 
        conda create -n vcf-kit \
              python3=${{ matrix.python-version }} \
              pytest \
              pytest-cov \
              numpy \
              scipy \
              cython \
              biopython \
              bwa \
              samtools \
              bcftools \
              vcftools \
              blast \
              primer3=2.5.0

    - name: Install 
      run: python setup.py install

    - name: Test vcf-kit
      run: py.test --verbose --cov-report=term --cov=vcfkit tests
    
    - name: Coverage
      run: coveralls

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      if: startsWith(github.ref, 'refs/tags')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: true
        prerelease: false

    - name: Publish a Python distribution to PyPI
      uses: pypa/gh-action-pypi-publish@master
      if: startsWith(github.ref, 'refs/tags')
      with:
        user: __token__
        password: ${{ secrets.PYPI_PASSWORD }}

    # - name: publish-to-conda
    #   uses: fcakyon/conda-publish-action@v1.3
    #   with:
    #     subdir: 'conda'
    #     anacondatoken: ${{ secrets.ANACONDA_TOKEN }}
    #     platforms: 'win osx linux'