# Build dockerfile on change
name: Test

on:
  - push

jobs:
  test_and_publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install curl headers
      run: |
        sudo apt-get install libcurl4-openssl-dev
    - uses: actions/setup-python@v2
      with:
        python-version: '3.7' 
    - run: python setup.py install

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      if: startsWith(github.ref, 'refs/tags')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: true
        prerelease: false

    - name: Publish a Python distribution to PyPI
      uses: pypa/gh-action-pypi-publish@master
      if: startsWith(github.ref, 'refs/tags')
      with:
        user: danielecook
        password: ${{ secrets.pypi_password }}